# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170417_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='accounts/avatars/default.png', upload_to='accounts/avatars', verbose_name='Avatar'),
        ),
    ]
