# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170702_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1),
        ),
    ]
