# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171218_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invited_to_friends',
            field=models.ManyToManyField(related_name='_userprofile_invited_to_friends_+', to='accounts.UserProfile'),
        ),
    ]
