# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_invited_to_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='invited_to_friends',
            field=models.ManyToManyField(related_name='inviters', to='accounts.UserProfile'),
        ),
    ]
