# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatedUpdatedModel',
        ),
    ]
