# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-14 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composcommit',
            name='title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
