# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspace', '0002_auto_20171014_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='compos',
            name='compos_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compos',
            name='tag',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='composbranch',
            name='parent_commit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_branches', to='workspace.ComposCommit'),
        ),
        migrations.AlterField(
            model_name='composbranch',
            name='branch_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='composcommit',
            name='commit_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='compos',
            unique_together=set([('tag', 'author'), ('compos_id', 'author')]),
        ),
    ]
