# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 19:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_auto_20170502_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literarycomposbranch',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_literary_composes_branches', to=settings.AUTH_USER_MODEL),
        ),
    ]
