# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_auto_20171016_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='composcommit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workspace.ComposCommit'),
        ),
    ]
