# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_composcommit_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compos',
            name='tag',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='composbranch',
            name='tag',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='composcommit',
            name='tag',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
