# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_composcommit_commit_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compos',
            name='title',
            field=models.CharField(default='New composition', max_length=512),
        ),
    ]
