# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0011_compos_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='compos',
            name='origin',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copied_composes', to='workspace.Compos'),
        ),
    ]
