# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_compos_origin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='composbranch',
            unique_together=set([('tag', 'compos'), ('id', 'compos')]),
        ),
        migrations.AlterUniqueTogether(
            name='composcommit',
            unique_together=set([('tag', 'branch'), ('id', 'branch')]),
        ),
    ]
